_catamaran_generate_openssl_cnf()
{
	# here, we essentially duplicate and extend CATAMARAN_INTER_CA with the root CA
	local -a ca_ids=(${CATAMARAN_ROOT_CA[ID]})
	local -a ca_refs=(CATAMARAN_ROOT_CA)

	local inter_ref
	for inter_ref in ${!CATAMARAN_INTER_CA[@]} ;do
		ca_ids+=($inter_ref)
		ca_refs+=(${CATAMARAN_INTER_CA[$inter_ref]})
	done

	cat <<EOS
# Automatically generated by catamaran; do not edit!

####################################################################
[ ca ]
default_ca = CA_${CATAMARAN_ROOT_CA[ID]}
EOS

	local idx
	for ca_id in ${ca_ids[@]} ;do
		cat <<EOS
####################################################################
[ CA_${ca_id} ]

dir = ${ca_id}.cadb
certs = \$dir/certs # Where the issued certs are kept
crl_dir = \$dir/crl # Where the issued crl are kept
database = \$dir/index # database index file.
new_certs_dir = \$dir/newcerts # default place for new certs.
certificate = \$dir/ca.pem # The CA certificate
serial = \$dir/serial  # The current serial number
crlnumber = \$dir/crlnumber # the current crl number
crl = \$dir/crl.pem  # The current CRL
private_key = \$dir/private/ca.key # The private key

default_days = 730 # how long to certify for
default_crl_days= 30 # how long before next CRL
default_md = default # use public key default MD
preserve = no # keep passed DN ordering

# A few difference way of specifying how similar the request should look
policy = policy_match
copy_extensions = copy

EOS
	done

	cat <<EOS

# Catamaran enforces a matching Organi[sz]ation field across certificates, but nothing more
[ policy_match ]
countryName = optional
stateOrProvinceName = optional
localityName = optional
organizationName = match
organizationalUnitName = optional
commonName = supplied
emailAddress = optional

####################################################################
[ req ]
default_bits = 4096
default_keyfile  = privkey.pem
distinguished_name = req_distinguished_name
attributes = req_attributes
x509_extensions = v3_ca # The extensions to add to the self signed cert

# This sets a mask for permitted string types.
string_mask = utf8only

[ req_distinguished_name ]
0.organizationName = Organization Name is enforced by Catamaran
0.organizationName_default = ${CATAMARAN_ORG}

commonName = Common Name (e.g. server FQDN or purpose-specific name of CA)
commonName_max = 200

emailAddress = Email Address
emailAddress_max = 96

[ req_attributes ]
challengePassword = A challenge password
challengePassword_min = 4
challengePassword_max = 20


EOS

	for ca_id in ${ca_ids[@]} ;do
		cat <<EOS
[ user_cert_${ca_id} ]
# These properties/extensions are added when CA ${ca_id} signs a [non-CA] request.

# This goes against PKIX guidelines but some CAs do it and some software
# requires this to avoid interpreting an end user certificate as a CA.
basicConstraints=CA:FALSE

keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
nsComment = "Catamaran/${ca_id}"

# PKIX recommendations harmless if included in all certificates.
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer

EOS
	done
	cat <<EOS
[ v3_ca ]
# These properties/extensions are for making the CA certificates (root and intermediate).
# Don't use them for any end-user certificates.

subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer
basicConstraints = critical,CA:true
keyUsage = critical,cRLSign, keyCertSign

[ crl_ext ]
# CRL extensions.
# Only issuerAltName and authorityKeyIdentifier make any sense in a CRL.
authorityKeyIdentifier=keyid:always
EOS
}
